### ISSUE TITLE
benchmark fails to build with ghc-9.6

### ISSUE THREAD

**Issue by juhp** [informatikr/hedis#214]
```
       /var/stackage/work/unpack-dir/unpacked/hedis-0.15.2-5411e1a05b7576461adea21b3272f243b1ba5cd34963df2bf59fbdf1f3670aa8/benchmark/Benchmark.hs:44:16: error: [GHC-58481]                                                                                            
           parse error on input ‘<-’                                                                                                
           Suggested fix: Possibly caused by a missing 'do'?      
          |    
       44 |         startT <- getCurrentTime                                                                                        
          |                ^^
```

**Comment by ysangkok** [comment]
Already fixed: https://github.com/informatikr/hedis/pull/202/files#diff-cca066bdbd45e973c045766b75e3b72599f5fea2be04b34dca097836a737b7fa

Just needs a release

**Comment by qnikst** [comment]
@ysangkok  thanks for the reply!

I'll start process of getting an access to hackage, unfortunately @k-bx does not reply on email, so I'll have to go via hackage trustees. As for release I'd like to sort out #213.

Likely it will be possible to make another version of 0.15 before a major release with GHC-9.6 support.

**Comment by qnikst** [comment]
Fixed in #201  Thanks!
